[package]
name = "vim9jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.29"
num = "0.4.0"
rmp = "0.8.10"
rmpv = "1.0.0"
anyhow = "1.0.52"

[dev-dependencies]
pretty_assertions = "1.0.0"

[features]
