[package]
name = "vimfuncs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "0.11.1"

[build-dependencies]
anyhow = "1.0.66"
phf_codegen = "0.11.1"
